# main text of home
title: Omid Mostafaei Nia
bio: Senior Business Data Analyst | Marketplace & Operations Analytics | KPI Systems, Dashboards & Incident Detection

# twitter / SEO summary info
description: Senior Business Data Analyst with 5+ years of experience in marketplace, operations, and performance analytics. Focused on KPI frameworks, dashboards, anomaly detection, vendor performance, and data-driven decision systems.

external-image: false
picture: assets/images/profile.jpg

dark-theme: auto

resume: true
resume-external: false
resume-url: assets/Omid Mostafaei Nia - CV.pdf

url: https://omidmno2.github.io
permalink: /:title/

linkedin: omidmno2
github: omidmno2
researchgate: Hossein-Mostafaei-Nia
orcid: 0009-0001-4151-6287
email: omidmostafaei@yahoo.com

authors:
  johndoe:
    name: Omid Mostafaei Nia
    bio: Senior Business Data Analyst focused on marketplace analytics, operational performance, and decision systems.
    external-image: false
    picture: assets/images/profile.jpg

width: normal

# if you don't need projects, comment the *projects* configs below
projects: true
# if you don't need "about" or "blog", comment them out below
about: true
blog: true
dashboards: true
papers: true

read-time: true
show-tags: true
related: true
post-advance-links: [dashboards]
show-author: true
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
